general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "VictorMono Nerd Font Mono", style = "Regular" }
size = 12.0

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.95
